services:
  career-compass-gin-dev:
    build:
      context: .
      target: final
    container_name: career-compass-gin-dev
    env_file: .env.dev
    ports:
      - 3000:3000
    depends_on:
      postgres-dev:
        condition: service_healthy
  postgres-dev:
    image: postgres
    restart: always
    container_name: postgres-dev
    volumes:
      - career-compass-gin-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=career-compass-gin-dev
      - POSTGRES_PASSWORD=career-compass-gin-dev
      - POSTGRES_DB=career-compass-gin-dev
    ports:
      - 5555:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  mailhog-dev:
    image: mailhog/mailhog
    container_name: mailhog-dev
    ports:
      - 1025:1025
      - 8025:8025

  career-compass-gin-prod:
    build:
      context: .
      target: final
    container_name: career-compass-gin-prod
    env_file: .env.prod
    ports:
      - 3000:3000
    depends_on:
      postgres-prod:
        condition: service_healthy
  postgres-prod:
    image: postgres
    restart: always
    container_name: postgres-prod
    volumes:
      - career-compass-gin-prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=career-compass-gin-prod
      - POSTGRES_DB=career-compass-gin-prod
    env_file: .env.prod
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  career-compass-gin-dev:
  career-compass-gin-prod:
